# Generated by Django 5.1.3 on 2025-04-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("subject", models.CharField(blank=True, max_length=200, null=True)),
                ("message", models.TextField()),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("quote", "Request a Quote"),
                            ("general", "General Inquiry"),
                        ],
                        default="general",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
