# Generated by Django 5.1.3 on 2025-04-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={},
        ),
        migrations.RemoveField(
            model_name="contact",
            name="contact_type",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="is_processed",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="subject",
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(max_length=100),
        ),
    ]
