# Generated by Django 5.1.3 on 2025-04-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_options_remove_contact_contact_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_type",
            field=models.CharField(
                choices=[("quote", "Request a Quote"), ("general", "General Inquiry")],
                default="general",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
