# Generated by Django 5.2 on 2025-04-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_projectinquiry_contact_contact_type_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinquiry',
            name='project_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
