# Generated by Django 5.2 on 2025-04-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_projectinquiry_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinquiry',
            name='project_id',
        ),
        migrations.AlterField(
            model_name='projectinquiry',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectinquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
